name: nx-libs CI

on:
  push:
    branches: [ 3.6.x ]
  pull_request:
    branches: [ 3.6.x ]

jobs:
 build:
  name: Build on ${{ matrix.cfg.container }} - ${{ matrix.cfg.cpp-version }}
  runs-on: ubuntu-latest
  container: ${{ matrix.cfg.container }}
  strategy:
    fail-fast: false
    matrix:
      cfg:
        - { container: 'ubuntu:16.04', cpp-version: gcc }
        - { container: 'ubuntu:16.04', cpp-version: clang }
        - { container: 'ubuntu:20.04', cpp-version: gcc }
        - { container: 'ubuntu:20.04', cpp-version: clang }
        - { container: 'buster:latest', cpp-version: gcc }
        - { container: 'buster:latest', cpp-version: clang }
        - { container: 'centos:7', cpp-version: gcc }
        - { container: 'centos:7', cpp-version: clang }
        - { container: 'centos:8', cpp-version: gcc }
        - { container: 'centos:8', cpp-version: clang }
        - { container: 'fedora:latest', cpp-version: gcc }
        - { container: 'fedora:latest', cpp-version: clang }
        - { container: 'buster:latest', cpp-version: gcc }
        - { container: 'buster:latest', cpp-version: clang }

  steps:
  - name: Install compiler ${{ matrix.cfg.cpp-version }}
    shell: /bin/sh
    run: |
      case "${{ matrix.cfg.container }}" in
        ubuntu*|buster)
          cat /etc/debian_version
          ${{ matrix.cfg.container }} --version
          apt-get update -q -y
          apt-get install -q -y ${{ matrix.cfg.cpp-version }}
          ;;
        fedora*)
          cat /etc/fedora-release
          ${{ matrix.cfg.container }} --version
          dnf -y update
          dnf -y install ${{ matrix.cfg.cpp-version }}
          ;;
        centos*)
          cat /etc/centos-release
          ${{ matrix.cfg.container }} --version
          yum -y update
          yum -y install ${{ matrix.cfg.cpp-version }}
          ;;
      esac
